permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: rdiscount

# 作者信息
author: 
  name: shoron
  email: yushouren123.com
  link: shoron.github.io
  github: http://github.com/shoron

# 站点信息
title:  shoron's blog
description: My personal blog
url: shoron.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/boy.jpg
favicon: /public/img/boy.jpg

# disqus 设置
disqus:
  shortname: shoron

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档